### PR TITLE
Scenario 42 fix-ups

### PR DESCRIPTION
**Pull request by EnSnack**
Section 135.2 deliberately left empty because we didn't make it into that room, also special rule and scenario effect not added yet, will be done later.

### CODE REVIEW

**Comment by EnSnack** [comment]
!spoiler

Quickly added rules, the curse rules (non-scenario effect) are not correct, it is only [!spoiler]non-lurker[!spoiler] characters that get 2 curses to their deck, but I didn't have time to check how I would do that.

**Comment by Lurkars** [comment]
You can use regex for names, not sure if this helps.

**Comment by EnSnack** [comment]
> You can use regex for names, not sure if this helps.

I guess in theory you could manually search the lurker names exclude all but like `^(?!.*Geminate).*$` (Geminate isn't a lurker, just example), but our group doesn't know all characters who are lurkers, and I don't wish to spoil myself on those characters until we unlock them. The alternative would be adding the race for each character like lurker, harrower, quatryl etc. but idk how much its used outside of this one scenario. It may be worth coming back to when I know more about the characters.

**Comment by EnSnack** [comment]
I realized that name wasn't their literal character name (my apologies), I still don't know if coral and kelp are the only lurkers, but those are the ones I know, I did notice that
> data/fh/character

character files had characterClass which features their race, that could work? I couldn't make it work in identifier, probably because it isn't coded in, and I wasn't sure if its worth coding in.

**Comment by Lurkars** [comment]
I think for now this is fine, and I will think about if it's worth adding some mechanic for this. Maybe it comes in more scenarios, that it's class dependent.

**Pull request merged**
