### PR TITLE
Updates to Crimson Scales scenarios 31 - 66

### PR DESCRIPTION
**Pull request by TheSquinter**
Not sure what happened with the merges and commits. Hopefully the PR works OK.

This has been completed for Scenarios 31 - 66:
- Updated any missing section names, links and markers
- Added treasures
- Added scenario effects
- Added scenario rewards and requirements
- Added scenario special rules where needed
- Checked and updated monster counts
- Created parts A and B for Scenario 32, depending on decision from Scenario 30
- Tried adding boss 53 special rules and ability decks - had complicated rules
- Created custom monsters for Scenarios 32, 39, 55, 60
- Updated some stats for existing custom monsters
-
Also:
- Added CS Item 41 for solo reward
- Fixed name of Items 12 and 39
- Updated CS rewards to use GH items for Scenarios 6, 10, 19 and 21

### CODE REVIEW

**Comment by TheSquinter** [comment]
With those conflicts:

- data/cs/scenarios/19.json - Should be `"48-gh"` for GH reward item
- data/cs/scenarios/21.json - Should be `"99-gh"` for GH reward item
- data/cs/scenarios/30.json - Removed the unlock and rewards as that is handled through the conclusions Section 32C and 34A

**Comment by TheSquinter** [comment]
I also noticed there are duplicate files for the solo scenarios and sections in different locations:
`gloomhavensecretariat\data\solo\scenarios` and `solo\sections`

I've been only making updates to the files in:
`gloomhavensecretariat\data\cs\scenarios` and `cs\sections`


E.g. Scenario 56 for Target solo scenario
`cs\scenarios` and `cs\sections` -  56.json and 63B.json
`solo\scenarios` and `solo\sections` - solo37_target.json and solo37-63B.json

**Comment by Lurkars** [comment]
Habe to take a deeper look at this for merging if you have doubts.

For the solo scenarios: no idea 😅 I just parsed most data from XHA/TTS. But from organizational standpoint, the solo scenerios should go to solo edition. Maybe it's a bit confusing, because on other editions the solo scenerios were an extra, where on CS they're directly included. Anyways, for GHS I like it more too be able to hide/disable solo scenerios and therefore they should be in different edition.

**Comment by TheSquinter** [comment]
Only doubting cause it's included the changes from #271 for some reason and that warning about conflicts.

The updates I made here include the CS solo scenarios (56 - 66) in the root `data\cs` folders, so up to you if you want to move them out or merge them with the data in `data\solo`. Just not sure how that works with the custom monsters and decks.

I'd thought better to have the data for the solos together with their editions and use a `solo` scenariorule tag or something to hide or separate them in the app if needed.

**Pull request merged**
