### PR TITLE
Do not remove Algox's pernament regenenaration

### PR DESCRIPTION
**Pull request by gkaragia**
Algox has permanent regeneration with his 'One with the Mountain' card. However, whenever he gets damaged the regeneration is removed. 

The card is crucial to the class' mechanics so I suppose that everyone will use it and it makes sense to never automatically remove regeneration from this class.

### CODE REVIEW

**Comment by Lurkars** [comment]
This doesn't make sense to me. First: it's an ability to play, so possible to not pay it and gain it normal and then lose it. Second: I see it mentioned in Fist class with reference to ability card, but not in Snowflake for example. Does SF have similar ability card? Nevertheless, I also don't like those hard exception. To me makes more sense to mark a condition as permanent somehow. I will think about this.

**Comment by gkaragia** [comment]
Ah sorry didn't realise that algox goes for SF too. I meant to do this for Fist only.

Regarding Fist, this is a must have as I don't see the class being used some other way (it has an 8 card hand). As it is now, you have to apply regenerate every turn. Permanent buffs makes and they might be used in other cases too.

**Comment by Lurkars** [comment]
I know at least from some special scenario rules where monsters have a permanent condition. This is currently achieved by open an apply dialog every time a monster looses this condition. So a feature with a permanent condition state makes way more sense. I will work on this. Because I still don't think it is correct to have this hard-coded to fist. Because it doesn't make sense for you, doesn't mean someone else want to play different and than is stuck on a regeneration condition!

**Comment by Lurkars** [comment]
I added permanent conditions with this: https://github.com/Lurkars/gloomhavensecretariat/commit/34306927e9fa47294175b7ccbf2c8f414f5e7546 I think this is better solution!

**Pull request closed without merging**
