### PR TITLE
2 small UI tweaks at party sheet

### PR DESCRIPTION
**Pull request by keinkurt**
To change this 
grafik
to this 
grafik

and this
grafik
to this
grafik

### CODE REVIEW

**Comment by keinkurt** [comment]
Now, with additional test I see the problem. It seems that the Pyroclast icon is too large and will produce the problem. Maybe it will be easier to fix the Pyroclast icon.

**Comment by keinkurt** [comment]
... and in my first screenshot the problem seems to be the Prism icon. Generally the Character icons should be squared...

**Comment by keinkurt** [comment]
Now, I changed back the sizing of the icons on the champain sheet and fixed some of the fh character icons. With this, the issue should be fixed.

**Comment by Lurkars** [comment]
I just changed icons to fixed height to solve the issue. So will close this PR. Will still think about making all icons same base size.

**Comment by Lurkars** [comment]
So check if [v0.89.0](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.89.0) fixes that for you.

**Pull request closed without merging**
