### PR TITLE
[ko] update locales

### PR DESCRIPTION
**Pull request by derornos**
src/assets/locales
- ko.json

data
- gh/label.json
- jotl/label.json
- fh/label.json

### CODE REVIEW

**Comment by derornos** [comment]
Hi, @Lurkars
I'm wondering how I can translate the names of the items and the names of the scenarios.

Thanks.

**Comment by Lurkars** [comment]
Scenarios can be translated in data label files, see German translations for example:
https://github.com/Lurkars/gloomhavensecretariat/blob/main/data/gh/label.json#L446

Items do not have translations yet, but become same as for scenarios in edition data.

**Comment by derornos** [comment]
Hi, @Lurkars !

Now is it possible to translate the items, please let me know how and I will try.
I'd also like to work on the battle goal and charactor deck cards if possible.

Thanks.

**Comment by Lurkars** [comment]
Thanks for your efforts! Good point, I neglected to use i18n a bit in adding all that data. I will update the changes to at least move the battle goals and item texts into the label files, so you should be able to translate them. By the way, I am not sure what you mean by character deck cards. The actual character decks are still not supported. I have old test data for Brute and Mindthief, but nothing else, so not worth bothering with.

**Comment by Lurkars** [comment]
I will move the `label.json` (and `label-spoiler.json`) to seperate files in `label` (and `label-spoiler`) folder, so for example label files for GH are then `data/gh/label/en.json`, `data/gh/label/de.json`, `data/gh/label/fr.json` and `data/gh/label/ko.json`.

I hope that will make the files easier to handle and read!

**Comment by derornos** [comment]
thanks : )

**Pull request merged**
