### PR TITLE
Updates to Scenarios 27, 28, 29, 30, 35 and 36

### PR DESCRIPTION
**Pull request by TheSquinter**
Made the following changes:

Scenario 20
- Updated spawn rules to
- Added custom text to objectives

Scenario 27
- Section 95.1 - Fixed 2 objectives spawning for 3 characters (should be only 1)
- Section 71.5 - Added Treasure 36
- Section 148.4 - Added Treasure 24

Scenario 28
- Added missing archer standee
- Updated guard standees
- Added Treasures 48 and 60
- Added 2 objectives with their movement actions listed
- Added monster spawn rules

Scenario 29
- Added scenario effect reminder:  Each character gains brittle
- Added Algox guards and archers to monsters list
- Added treasure 45

Scenario 30
- Added scenario effect reminder:  Each character gains brittle
- Added per round spawn rules
- Added rule to open Section 53.2 at the start of round 12
- Created file for Section 53.2
- Added treasure 45

Scenario 35
- Added scenario effect reminder:  Each character gains muddle
- Section 104.4 - Adding missing Ruined Machine standee for 4 players

Scenario 36
- Added scenario effect reminder:  Each character suffers 2 damage
- Added starting objectives

Scenario 37
- Section 70.1 - Fixed monster standee list for all player counts

### CODE REVIEW

**Comment by TheSquinter** [comment]
Trying to work out how to add a custom marker for objectives. 

image

The idea is to remind players to spawn a Flaming Bladespinner at 'Glowing Orb' when objective is destroyed. 
Current code:

 ```
 "objectives": [
    {
      "name": "Cabinet",
      "health": "Cx(L+2)",
      "initiative": 1,
      "count": 4,
      "actions": [
        {
          "type": "custom",
          "value": "When destroyed:",
          "small": true
        },
        {
          "type": "spawn",
          "value": "monsterStandee",
          "valueObject": [
            {
              "monster": {
                "name": "flaming-bladespinner",
                "player2": "normal",
                "player3": "normal",
                "player4": "elite"
              },
              "marker": "Glowing Orb"
            }
          ]
        }
      ]
    }
  ],
```

Also trying to work out how to show the Flaming Bladespinner cards so players can spawn them. With 'Automatic Standees' set, the enemy cards do not show.

**Comment by TheSquinter** [comment]
With Scenario 28, the spawn rules state that "At the start of each **even** round, spawn one Guard and one Archer. Normal for 2 players, elite **each second** spawning for 3 and both elite for 4"

What's the best way to implement the 3 player rule? It should be:
Rounds 2, 6, 10, etc are normals
Rounds 4, 8, 12, etc are elites.

Current code:

 ```
 "rules": [
    {
      "round": "R % 2 == 0",
      "start": true,
      "spawns": [
        {
          "monster": {
            "name": "algox-archer",
            "player2": "normal",
            "player3": "normal",
            "player4": "elite"
          },
          "marker": "d"
        },
        {
          "monster": {
            "name": "algox-guard",
            "player2": "normal",
            "player3": "normal",
            "player4": "elite"
          },
          "marker": "e"
        }
      ]
    }
  ],
```
I tried something like 
`"round": "R % 4 == 0",`

But then they get 2 lots of prompts at rounds 4, 8, 12.

**Comment by Lurkars** [comment]
First of all, please create PR when you think you're finished. Creating PR and then working on it triggers E-Mails for every change. So work on the stuff and when you thinks it's in a merge-able change, then create PR. Otherwise I will not know if I can merge this or not and have to ask when it's finished. I don't even know now: Is this done and only open questions for future? Or is this in a state, where it's not merge-able because of questions?

If you having issues, don't know how to do things, don't discuss this here in PR. Open an Issue/Discussion and ask for help.

Anyway thanks for your work, really appreciate this!!!

**Comment by TheSquinter** [comment]
Thanks for the advice and patience, I'm definitely still learning how it all works. I will only do the PR when ready in the future.

I do still need help with the above comment though before we can merge if that's ok. If it's harder than it looks, I'll just remove those changes.

**Comment by Lurkars** [comment]
So to your issues, I just added to highlight spawns on Objectives, so they are clickable. Though no idea how I can accomplish adding the corresponding monster when interactive actions are disabled. Anyways, you can just take your code as it is besides the `"marker": "Glowing Orb"`, that is not supported, markers are only `1-9a-h` or so, so only the map marker tokens available in physical. So you would just add a `custom` sub-action to reference the Glowing Orb.

**Comment by Lurkars** [comment]
Ah and short info: what's general missing for fulfilling some scenario special rules and what I need to implement (and going to, just no idea how to do best) is like a "Kill counter". Some rules are like `if [C] enemies killed, spawn...` or so. This is not possible by now!

**Comment by TheSquinter** [comment]
Thanks, this one is ready to merge now.

**Pull request merged**
