### PR TITLE
Updated Treasure Data (2 minor issues remain)

### PR DESCRIPTION
**Pull request by Doctawin**
I've double checked the treasure data file and corrected a few typos. I've also inputted the treasures into all sections; however, there are 2 issues:

- Sections 2.1, 3.2, and 6.3 are currently missing - I'll see if I have some free time later in the week to help input those three missing sections and the treasure data
- ~~Section 177.2 contains 3 treasures (20, 51, 55) and I wasn't sure how this data should be entered.~~

Outside of the above issues, all treasure data should now present and double checked. 

Edit: I looked back at my spreadsheet of chest values and some of them appear to be missing from my list. I need to double check what happened there. 

Edit 2: Ah, the ~20 missing chest values are located in the initial scenario files. I'll start entering those in.

### CODE REVIEW

**Comment by TheSquinter** [comment]
Nice one. For multiple treasures, I just updated it for Scenario 28 - looks like you can do it like this:

```
      "treasures": [
        48, 60
      ]
```

**Comment by Doctawin** [comment]
> Nice one. For multiple treasures, I just updated it for Scenario 28 - looks like you can do it like this:
> 
> ```
>       "treasures": [
>         48, 60
>       ]
> ```

Great, I'll get the missing data in :)

**Comment by Doctawin** [comment]
> Are you planning to add any missing treasures to the scenarios too? I'm currently going scenario by scenario to update various rules and have been adding missing treasures as I go (like Scenario 28). I added treasures to sections 71-5 and 148-4 as part of Scenario 27, but I see you've updated those sections yourself.
> 
> I'll ignore the sections now if you've already done the work! :)

Yeah, all section treasures should be in except for sections 2.1, 3.2, 6.3, and 177.2, and I'm currently working on inputting the scenario ones :)

**Comment by Doctawin** [comment]
Actually, I don't know much about github. Will the changes be correctly merged if we're editing the same files?

**Comment by TheSquinter** [comment]
> Actually, I don't know much about github. Will the changes be correctly merged if we're editing the same files?

Not sure haha. Maybe leave the Scenario 28 one just in case? Cause that one currently has a lot of changes I'm added in, including the treasures.

**Comment by TheSquinter** [comment]
I'm curious to see how this merges as I updated Scenario 26 yesterday as part of #178 which added a special rule as well as treasure 73. Wonder if this merge will remove that special rule?

Also, Scenario 29's treasure should be 45, not 49 :)

**Comment by Doctawin** [comment]
> I'm curious to see how this merges as I updated Scenario 26 yesterday as part of #178 which added a special rule as well as treasure 73. Wonder if this merge will remove that special rule?
> 
> Also, Scenario 29's treasure should be 45, not 49 :)

Yeah, hopefully, there's a nice built-in way to do some selectively merging. D'oh, thanks for pointing out that typo!

**Comment by Lurkars** [comment]
So is this ready to merge now?

**Comment by TheSquinter** [comment]
@Doctawin FYI I have created the missing sections as part of my pass going scenario by scenario and added those treasures in as I come across it.

**Pull request merged**
