### PR TITLE
fix target all availabilities

### PR DESCRIPTION
**Pull request by keinkurt**
Hi Lurkars,

first thanks for your great work on this project!

Last scenario we realised by seeing the Lukar Soldiers, that the Target All availability is buggy and the card is showing target 0. I tried to fixed it in the way you will see here. Hopefully it's correct. Also, I fixed it on other Monster classes, in exception of the Sun Daemon. This availability looks more complicated and I doesn't want to spoiler me to much.

Best regards,
Christian

### CODE REVIEW

**Comment by TheSquinter** [comment]
You're right, it does display incorrectly.
With this change it looks like it changes it to:
image

The actual card looks like this:
fh-ma-lus-1

**Comment by Lurkars** [comment]
Wasn't able to quick reply, bit yes. This is actually a display bug, the card data is correct and shouldn't change, because I want too match always the original card (when all calculations turned off!). This PR would change the card like @TheSquinter mentioned. 

I will fix the issue, but sadly have to decline your PR here.

**Comment by keinkurt** [comment]
Ok, that's fine to me. I'm also tried to fix this in the code, but with no success. Should I create an issue for it?

**Comment by Lurkars** [comment]
No, I just referenced in the commit. Should be fixed now in [v0.59.5](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.59.5)

**Pull request closed without merging**
