### PR TITLE
New next standee setting

### PR DESCRIPTION
**Pull request by EnSnack**
Not sure if this is a good idea, but I thought it was helpful, another idea might be to make it a possibility in the all standees button?
image

### CODE REVIEW

**Comment by Lurkars** [comment]
Clicking on this menu and then "add next" is not shorter then clicking the + icon and click on the next free number. So I don't really see any benefit on this here. 🤷‍♂️

**Comment by Lurkars** [comment]
To the main PR function: I think it should be niche house rule to select standees in order. Rules are clear, that numbers should be picked random, so I think whoever wants to change this, can just select the numbers as usual.

**Comment by EnSnack** [comment]
> Clicking on this menu and then "add next" is not shorter then clicking the + icon and click on the next free number. So I don't really see any benefit on this here. 🤷‍♂️

I more meant clicking the menu and then automatically assigning numbers from 1 to n BUT

> To the main PR function: I think it should be niche house rule to select standees in order. Rules are clear, that numbers should be picked random, so I think whoever wants to change this, can just select the numbers as usual.

I actually did not know this, the numerical order from 1 to n with elite first is a rule we played with since Gloomhaven, I guess we must've read the rules wrong back then and never bothered to check up on it. I guess you learn something new every day 😅

**Comment by Lurkars** [comment]
Haha yes, I learned so much rules just by getting reports for the app. 

Quote from page 13. GH rule book:
> Note that only monsters in the starting room are placed at the beginning of a scenario. Monster standees each have a number to determine the order in which they act during the turn (see Order of Action on p. 29 for details). **The standee numbers should be randomized when placed.**

I am pretty sure that hasn't changed for Frosthaven...let me look, page 11:
> All standees for a monster type are numbered and should be randomized upon placement .

**Pull request closed without merging**
