### PR TITLE
Scenario 71 fix-ups

### PR DESCRIPTION
**Pull request by EnSnack**
Is it possible to edit an existing objective? Objective c (artificer) should execute a move 2, heal 1 self during his turn only after Section 95.3 is opened

### CODE REVIEW

**Comment by Lurkars** [comment]
This is possible with trick:
Add objective to section, but not to room data, then trigger transfer rule.

Example:
[FC Section #52](https://github.com/Lurkars/gloomhavensecretariat/blob/main/data/fc/sections/52.json#L101)

(Corresponding: [FC Scenario #104](https://github.com/Lurkars/gloomhavensecretariat/blob/main/data/fc/scenarios/104.json))

**Comment by EnSnack** [comment]
> This is possible with trick: Add objective to section, but not to room data, then trigger transfer rule.
> 
> Example: [FC Section #52](https://github.com/Lurkars/gloomhavensecretariat/blob/main/data/fc/sections/52.json#L101)
> 
> (Corresponding: [FC Scenario #104](https://github.com/Lurkars/gloomhavensecretariat/blob/main/data/fc/scenarios/104.json))

I tried this, but I'm not entirely sure what input the value parameter of transfer takes, I just put 1 because I assumed it was related to objective id from previous scenario, though that didn't seem to work so do you mind telling me where I went wrong?

**Comment by EnSnack** [comment]
> > This is possible with trick: Add objective to section, but not to room data, then trigger transfer rule.
> > Example: [FC Section #52](https://github.com/Lurkars/gloomhavensecretariat/blob/main/data/fc/sections/52.json#L101)
> > (Corresponding: [FC Scenario #104](https://github.com/Lurkars/gloomhavensecretariat/blob/main/data/fc/scenarios/104.json))
> 
> I tried this, but I'm not entirely sure what input the value parameter of transfer takes, I just put 1 because I assumed it was related to objective id from previous scenario, though that didn't seem to work so do you mind telling me where I went wrong?

nvm figured out I forgot to add marker c to the artificer in objective, oops..

**Comment by Lurkars** [comment]
It's just the number of the objective in scenario-data objective list, like the number you wild put in the rooms objective list to spawn.

**Comment by Lurkars** [comment]
Have you tested this and ready to merge? If you create PRs like this, not ready to merge on start, just ping me with a comment, like you're done, so I know!

Thanks again for your work!

**Comment by EnSnack** [comment]
> Have you tested this and ready to merge? If you create PRs like this, not ready to merge on start, just ping me with a comment, like you're done, so I know!
> 
> Thanks again for your work!

Tested and all ready yep, thanks again!

**Pull request merged**
