### PR TITLE
Scenarios 19, 20, 25, 26 updates, added some scenario effects

### PR DESCRIPTION
**Pull request by TheSquinter**
My first GitHub contribution - hopefully this all works as expected.

Made the following changes:

Characters:
- Fixed Trap class not ignoring negative scenario effects

Scenario 4B
- Deleted Section 75-1 file as Scenario 4B was showing both sections 75.1 and 75.1B

Scenario 10
- Added scenario effect reminder: Each character discards one card

Scenario 11
- Added scenario effect reminder: Each character discards one card

Scenario 18
- Added scenario effect reminder: Each character gains curse

Scenario 19
- Added scenario effect reminder: Each character gains wound
- Added monster spawn rules for each round
- Created and linked to Section 75.2 at the end of Round 9
- Added objectives for Section 75.2

Scenario 20
- Added starting room objectives
- Added monster spawn rules for each **even** round
- Added objective to Section 14.3
- Still potentially required that I don't know how to do: 
- [ ] Add Flaming Bladespinner monster card to starting room (for below rule)
- [ ] Add custom value text to Metal Cabinet objective to say: "When destroyed, spawn one <Normal/Elite> Flaming Bladespinner at the Glowing Orb - Normal for 2-3, Elite for 4". 
I don't know how to make the text variable for 2-3 or 4 players.
- [ ] Reminder rules for every **odd** round after the first for all characters, character summons and Ruined Machines to suffer trap damage if occupying or adjacent to a power conduit or metal cabinet

Scenario 22
- Added scenario effect reminder:  Each character adds two -1 cards to their attack modifier deck

Scenario 23
- Added scenario effect reminder:  Each character gains poison

Scenario 25
- Added spawning info while objective is present for Section 58.2
- Added missing normal Robotic Boltshooter and normal Flaming Bladespinner for 4 players in section 58.2
- Added spawning info while objective is present for Section 61.2
- Updated monster room data for Section 61.2
- Added Treasure 74 to Section 61.2

Scenario 26
- Added Treasure 73
- Added rule to open Section 131.4 at the start of round 7

### CODE REVIEW

**Comment by TheSquinter** [comment]
In my testing I didn't realise you could just restart the npm and your local changes would apply with a force update in the app. I was doing a git add and commit each change to re-test, hence all the commits - my bad!

**Comment by TheSquinter** [comment]
Added additional commit with some more updates. All changes listed above.

**Comment by Lurkars** [comment]
> In my testing I didn't realise you could just restart the npm and your local changes would apply with a force update in the app. I was doing a git add and commit each change to re-test, hence all the commits - my bad!

You can also just open a terminal with `npm run watch` and on every file update the data get's build. Just refresh in Browser and you can test your changes!

**Comment by TheSquinter** [comment]
> > You can also just open a terminal with `npm run watch` and on every file update the data get's build. Just refresh in Browser and you can test your changes!

Ah that's great, thanks.

What's the best way to go from here? Should I fork a new version and make any more changes to that one and do a new PR? Or keep updating this PR with new commits?

**Comment by TheSquinter** [comment]
I left 3 tasks in as optional for Scenario 20 as I don't know how to implement it. 

- [ ] Add Flaming Bladespinner monster card to starting room (for below rule)
- [ ] Add custom value text to Metal Cabinet objective to say: "When destroyed, spawn one <Normal/Elite> Flaming Bladespinner at the Glowing Orb" (Normal for 2-3, Elite for 4) 
I can add the text, just don't know how to make the Normal/Elite part variable depending on player count.
- [ ] Reminder rules for every **odd** round after the first for all characters, character summons and Ruined Machines to suffer trap damage if occupying or adjacent to a power conduit or metal cabinet

But otherwise, I've finished with this one.

**Pull request merged**
