### PR TITLE
Fix Algox Carving

### PR DESCRIPTION
**Pull request by jorge-graca-sky**
# Description

Algox is a chest piece not arm.

Fixes # (link to related issue here)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Data fix (fixes incorrect data)

# Checklist:

- [ ] I have performed a self-review of my code
- [ ] I tried to follow the [KISS principle](https://en.wikipedia.org/wiki/KISS_principle)

### CODE REVIEW

**Comment by dhyanna** [comment]
I believe the official FAQ has this as an arm piece and *not* a chest piece as the first printing had the item erroneously as a chest piece

**Comment by Lurkars** [comment]
Yes you're right. Damn. Will revert this tomorrow.

**Comment by jorge-graca-sky** [comment]
damn I am sorry I even check on bgg's faq, but there is nothing there :( 

Where did you find this info?

**Comment by Lurkars** [comment]
It is there: [Official FAQ](https://boardgamegeek.com/thread/3001013/official-faq-for-frosthaven-no-rules-questions-ple), search for 225

**Pull request merged**
