### PR TITLE
Fixed an issue where the drag-hp event may get cancelled on iOS devices due to accidental scrolling

### LINKED ISSUE #397: Scrolling cancels the "drag to adjust health" gesture
### Describe the bug

On an iPad, any vertical touch scrolls the UI. It's very easy to accidentally scroll instead of adjusting the HP of an enemy by dragging horizontally. What's worse, the HP adjustment action is "cancelled" and the number representing the health change just floats in the UI without affecting the health of the enemy. 

Perhaps scrolling could be completely disabled if you touch a standee? At the very least, the drag should not be cancelled when scrolling starts.

I think the problem is line 136 in main.ts where we call `this.pointerInputService.cancel();` which causes `dragHpEnd` not to get called in `standee.ts`.

### Game Enviroment

Any scenario as long as you have enough characters and enemies to enable scrolling.

### To Reproduce

The easiest is to just use an iPad, but if you don't have one available you can do as follows as long as you have a laptop:

1. Use Chrome on a PC
2. Use the trackpad of your laptop to start scrolling. Stop scrolling but keep your fingers on the trackpad.
3. Use your mouse to adjust the health of an enemy by dragging. Don't let go of the mouse button.
4. Move your fingers on the trackpad to scroll more.

### Expected behavior

The scrolling should be prevented or at the very least, the dragging action should not be canceled.

### Gloomhaven Secretariat Version

v0.77.2

### Used Browser

Chrome

### OS

Windows 11

### Additional

_No response_

### PR DESCRIPTION
**Pull request by mhalttu**
This is my attempt to finally fix #397. It seems to work on iOS based on my brief testing. I also tested that it did not seem to break anything on Safari or Chrome on a Mac. Further testing is recommended, especially on Android.

Some discussion on the solution: https://stackoverflow.com/a/43275544/3331890

### CODE REVIEW

**Comment by Lurkars** [comment]
Can you also test to add this rule to `.no-pointer` instead (as https://github.com/Lurkars/gloomhavensecretariat/issues/397#issuecomment-1730285597). If this works, would be more elegant solution. I will test separate on android and desktop if this breaks anything.

**Comment by mhalttu** [comment]
Screenshot 2024-03-24 at 17 38 51

Is this what you had in mind? Unfortunately, that did not seem to have any noticeable effect on the iPad.

**Comment by Lurkars** [comment]
Yes, this is what I meant and bad it didn't have an impact. But okay, so I just test your PR and if it has no negative impact, I can just  merge.

**Comment by mhalttu** [comment]
Thanks! 

You might be interested to know that I briefly tested an approach, where I would dynamically apply the `touch-action` style when dragging started. It worked better than before my fix, but it was still a bit too unreliable. 

If you still want me to test some other approaches on iOS, just let me know!

**Pull request merged**
