### PR TITLE
Automatically apply item fh 178 "Tranquil shoes"

### PR DESCRIPTION
**Pull request by jorge-graca-sky**
Did the edit on the browser without testing... Do not merge blindly :D

### CODE REVIEW

**Comment by Lurkars** [comment]
Oh thought I found all useful applicable items, thanks. I think I will then just add this manually myself instead of merging this. Do you have more items missing that are good to implement?

**Comment by jorge-graca-sky** [comment]
> Oh thought I found all useful applicable items, thanks. I think I will then just add this manually myself instead of merging this. Do you have more items missing that are good to implement?

Okay thanks! :D Not that I know of, this pure self-interest because it randomly dropped on our game :P

**Comment by jorge-graca-sky** [comment]
Uhmmm this code does not respect Poison status :(

**Comment by Lurkars** [comment]
I now added item support with https://github.com/Lurkars/gloomhavensecretariat/commit/f062b22e14b0d92391f6f9df7f156fbede9ba3bc#diff-d9d55e551d9cc48536f05d0689051b1e52f81232f4316c502f7a5903f23e2d33, will come in next release!

**Comment by jorge-graca-sky** [comment]
@Lurkars Damn that was epic fast! thanks! 

One curiosity, why the "&& !entity.longRest" in the code? Some FAQ I missed?

**Comment by Lurkars** [comment]
> @Lurkars Damn that was epic fast! thanks!

Haha, quite long for my usual changes, but very busy with other stuff here...
 
> One curiosity, why the "&& !entity.longRest" in the code? Some FAQ I missed?

The Item says... `your initiative is 60 or higher and you are not performing a long rest`

> Also, is it not missing the usual: `if (entity.health > maxHealth) { entity.health = maxHealth; }` ?

The `applyCondition` also calling `checkHealth` where this is performed! And it's working, but just tested it and should be outside timeout, otherwise during highlight animation, you're over maxHp and then back. So thanks again for letting me test that.

**Pull request closed without merging**
