### PR TITLE
skip exhausted characters when tabbing through initiatives

### PR DESCRIPTION
**Pull request by sjbarag**
Focus used to not advance past an exhausted character's initiative input:

Now, we skip those characters while tabbing (leaving the previous focus cycling intact):

### CODE REVIEW

**Comment by Lurkars** [comment]
Your code is quite complex. If I reproduce the correctly, the issue is the following:

(only!) if an exhausted character is sorted before non-exhausted characters, the tab function does not work, because the exhausted character is blocking the order.

From my perspective and short testing the following change to `tabIndex()` is simple enough:
```
  tabindex(): number {
    return gameManager.game.figures.filter((figure) => figure instanceof Character && !figure.absent).sort((a, b) =>
      (a instanceof Character && b instanceof Character) ? ((a.exhausted && !b.exhausted) ? 1 : (!a.exhausted && b.exhausted) ? -1 : 0) : 0).indexOf(this.figure);
  }
```
So adding a simple `sort` line to the `tabIndex()` function is +1 line of code. Your code has +19 lines. Or am I missing something hear from a quick look?

**Comment by Lurkars** [comment]
Please reopen if I got this wrong. Otherwise this is now solved with https://github.com/Lurkars/gloomhavensecretariat/commit/b571222721fd31bb63e38ec3a5b47c54087de2f9

**Comment by sjbarag** [comment]
Oh neat! Yep, that took care of it — thanks for the quick fix :)

Looks like that broke tab cycling (going from the last element to the first on `tab`) but that's neither here nor there.

**Comment by Lurkars** [comment]
Haha, yes. Looking at this now again makes my code even more simple...

**Pull request closed without merging**
