### PR TITLE
show keyboard shortcuts when '?' pressed

### PR DESCRIPTION
**Pull request by sjbarag**
Demo:

### CODE REVIEW

**Review by Lurkars — COMMENTED** [review]
Is it necessary to enable this shortcut when other dialogs are opened? From my perspective it is enough to check for open dialogs like for the other shortcuts and remove all the dialog-ID stuff. (KISS)

**Comment by sjbarag** [comment]
> Is it necessary to enable this shortcut when other dialogs are opened? From my perspective it is enough to check for open dialogs like for the other shortcuts and remove all the dialog-ID stuff. (KISS)

The `?` shortcut doesn't do anything when other dialogs are opened 😃 I added the dialog ID bits so pressing `?` closes the shortcuts dialog if it's open, which felt natural. A quick pass through some web apps I have nearby shows there's no consistency across apps though:

| App | Shows Dialog on `?` | Dismisses on `?` |
| --- | ------------------- | ---------------- |
| Gmail | Yes | Yes |
| Google Calendar | Yes | No |
| Fastmail | No | N/A |
| Github | Yes | No |
| Spotify | Yes | Yes |
| Discord | No (Yes for Cmd-/) | No (Yes for Cmd-/) |

Seems like anything you choose will have some precedent 🤷

Want me to remove the dialog ID bits so `?` only opens (and doesn't close) the shortcuts dialog?

**Comment by Lurkars** [comment]
Since all dialogs can be closed with <kbd>ESC</kbd>, I don't think this extra close is necessary for especially this dialog.

**Comment by sjbarag** [comment]
> Since all dialogs can be closed with ESC, I don't think this extra close is necessary for especially this dialog.

Works for me! Done.

**Review by Lurkars — APPROVED** [review]

**Pull request merged**
